### PR TITLE
Minor typos

### PR DESCRIPTION
**Pull request by agcolom**
I believe these are two typos?

### CODE REVIEW

**Comment by LJWatson** [comment]
With thanks @agcolom

**Comment by agcolom** [comment]
I have now linked my github account to the W3C account. Sorry, I've been out of everything for a while! I'm not sure whether I can retrigger the IPR check...

**Comment by chaals** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by chaals** [comment]
Sorted in any case - thank you again.

**Pull request merged**
