### PR TITLE
Table row ordering 330

### PR DESCRIPTION
**Pull request by chaals**
Process the first `thead` and first `foot` elements, moving them to the
start and end of the table respectively. Process others as row groups
in the order they appear.

### CODE REVIEW

**Comment by chaals** [comment]
Hopefully fixes #330 minimally. 

Please review.

I'll raise a separate issue regarding whether we should try to enforce the ordering of table content, that is not required by browsers (unless IE/Edge needs it).

**Comment by adanilo** [comment]
LGTM.

**Comment by sideshowbarker** [comment]
@foolip gave me heads-up about this and asked if I could consider commenting on it from my perspective as a developer for the HTML checker.

I think the behavior of the HTML checker might break if I attempt to have it conform to this change.

The algorithm in https://html.spec.whatwg.org/multipage/tables.html#forming-a-table is not a “fantasy” algorithm to toy with cavalierly without understanding its purpose. And its purpose as I understand it is largely to help authors identify mistakes in their table markup they might otherwise have missed.

So it’s not something that UAs actually need to implement unless like the HTML checker they have some error-reporting function (e.g., in their devtools) to help authors catch inadvertent table-markup errors.

For more background on the relationship to the HTML checker, see the following:
- https://blog.whatwg.org/table-integrity-checker
- https://hsivonen.fi/thesis/html5-conformance-checker.html#table-integrity

So again speaking from my perspective as developer of a tool that is likely affected by this change, I would very much prefer to see this PR backed out until some further discussion about this can take place and until it’s clear that we can all be in agreement that this is actually a good change based on a clear understanding of the details of the algorithm and its overall purpose.

It would also be good to have @hsivonen weigh in on this if possible (since he wrote the corresponding code use by the HTML checker).

**Comment by zcorpan** [comment]
The result of the integrity checker is not really changed I believe. Cells can't overlap between row groups, AFAICT, and so it doesn't matter for the integrity checker what the relative order is, except maybe the order of the error messages. (Too many `thead` or `tfoot` elements will be reported as errors by the RELAXNG schema anyway, right?)

Apart from finding conformance errors, the table model is also used in the spec to associate header cells and data cells, which is something I think ATs typically do (but maybe haven't implemented the spec's algorithm for doing so).
https://html.spec.whatwg.org/multipage/tables.html#header-and-data-cell-semantics

This might have slightly better results for tables that have multiple `thead` or `tfoot` elements with the change.

**Pull request merged**
