### PR TITLE
Fixed the indentation for Examples 66 and 67 area of section 3.2.1

### PR DESCRIPTION
**Pull request by iandevlin**
I noticed incorrect indentation as I was reading this section, and this fixes it.

### CODE REVIEW

**Comment by LJWatson** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by LJWatson** [comment]
With thanks @iandevlin

**Comment by LJWatson** [comment]
BTW your name is included in the [Acknowledgements section](https://www.w3.org/TR/html52/acknowledgements.html#acknowledgements). It was there before, but wanted to make sure you knew.

**Comment by iandevlin** [comment]
@LJWatson Ah nice, thanks! One question, I saw that I can mark the PR as non substantive myself (in fact I did it on another PR, but that was meant as a test as I really didn't think it would work), but I assume that it is better for someone else to mark it as such rather than me doing it myself?

**Comment by LJWatson** [comment]
@iandevlin. I didn't know that was possible. Give it a go next time you submit a PR. We can confirm it when we merge the PR.

If you're interested, we can add you to the WebPlat WG as an Invited Expert? That'd put a stop to all the IPR bits. Let me know?

**Comment by iandevlin** [comment]
@LJWatson Me neither, hence I tried it and I was surprised that it worked.

Yes, please add me, that would be cool.

**Comment by LJWatson** [comment]
@iandevlin can you complete the [IE application](http://www.w3.org/2002/09/wbs/1/ieapp/)?

**Pull request merged**
