### PR TITLE
Changes between WD 2 and the FPWD

### PR DESCRIPTION
**Pull request by chaals**

### CODE REVIEW

**Comment by chaals** [comment]
Please don't merge this yet, I want to make a minor tweak first.

**Comment by chaals** [comment]
Ready to be merged - I believe :)

**Comment by stevefaulkner** [comment]
this commit had some nested link issues which i fixed in https://github.com/w3c/html/commit/a12882741ab53adeb69559031883359da43e463e

for reference you can't do things like:

`<a href="https://github.com/w3c/html/commit/755136d6b8f2e4d858bf5e4ee1baff1793ab702d">Add <{link/nonce}> to <{link}></a>`
as the `<{link/nonce}>` and `<{link}>` create links.

**Comment by chaals** [comment]
Sigh. Honest, sometimes I do smart things…

Yeah - thanks Steve ...

**Pull request merged**
