### PR TITLE
add rel=newcontext

### PR DESCRIPTION
**Pull request by sc0ttbeardsley**
This proposal is an attempt to resolve the window.opener.location.href issue with cross-origin (and same-origin UGC?) navigations when target="_blank". This issue has been discussed previously[1] and a bug[2] in chromium has existed since 2013. Besides using "rel=noreferrer" or setting window.opener=null via javascript there appears no clean solution to this problem.

I propose that a new rel=newcontext attribute be added which can be used to inform user agents that the navigation should be done in a new browsing context and, as a result, window.opener should be set to null. Many publishers wish to allow a referrer to be sent and the Referrer Policy[3] is moving towards a spec where there is more granular control over the document-level and even the link-level value of Referer (sic). Many sites wish to send the origin, for instance, and in these cases they cannot use "rel=noreferrer". This leaves them only Javascript to deal with this issue. I think there should be a way to do this via HTML only.

Here is a quick summary and demo of the issue[4].

--
[1] https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jan/0002.html
[2] https://code.google.com/p/chromium/issues/detail?id=168988
[3] http://w3c.github.io/webappsec/specs/referrer-policy/
[4] http://hardstatics.com/thrower.html

### CODE REVIEW

**Comment by burgerbrains123** [comment]
Er. Sorry wrong person. I think it could work though.
Kindest Regards.

-----Original Message-----

**Comment by sc0ttbeardsley** [comment]
See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=28821

**Comment by burgerbrains123** [comment]
Scott,
This is the second time you have emailed me on the matter.
You are emailing the wrong person. please check that you are sending the
email to the right person.
it is quite hard to accidentaly send an email to spastichicken@gmail.com so
you are either very
unobservent (no offense) or intend to email me thinking i am somebody else.
so, please. make sure you email the right person.

kindest regards,
Sam.

**Comment by sc0ttbeardsley** [comment]
@burgerbrains123 sorry, it looks like you are subscribed to this PR. I believe you can remove yourself from "watching" this by clicking the "unsubscribe" button in github UI.

**Comment by burgerbrains123** [comment]
Ok, it was coming through as a direct email from you though. Sorry for the misunderstanding. I was just thinking... he has the wrong person and won't stop sending stuff 😀.

On 16 June 2015, at 7:53 PM, Scott Beardsley <notifications@github.com> wrote:

@burgerbrains123 sorry, it looks like you are subscribed to this PR. I believe you can remove yourself from "watching" this by clicking the "unsubscribe" button in github UI.

**Comment by sc0ttbeardsley** [comment]
duplicated by https://github.com/whatwg/html/pull/290 closing this one...

**Pull request closed without merging**
