### PR TITLE
Port WindowOrWorkerGlobalScope mixin. (#522)

### LINKED ISSUE #522: Port the `WindowOrWorkerGlobalScope` mixin.
https://html.spec.whatwg.org/#windoworworkerglobalscope-mixin does not exist in W3C's HTML. It would be nice if it did.

### PR DESCRIPTION
**Pull request by cynthia**
- Upstream: whatwg/html@cdd48e1f

Should be enough to resolve #522 . (Boilerplate work for getting Workers up to date.)

### CODE REVIEW

**Comment by arronei** [comment]
👍

**Comment by scshepard** [comment]
Hi, I'm a character blood hunt; what is the meaning the special character in your email that looks 01f44d? Is it ascii or a emoji?

Thanks!

**Comment by adanilo** [comment]
@scshepard ASCII < 128. THUMBS UP SIGN' (U+1F44D).

**Comment by cynthia** [comment]
r? Anyone?

**Pull request merged**
