### PR TITLE
fix webgl2 idl link

### PR DESCRIPTION
**Pull request by chaals**
see #1215

### CODE REVIEW

**Review by edent — APPROVED** [review]

**Comment by edent** [comment]
The build fails on this - but I don't know why.

**Review by edent — CHANGES_REQUESTED** [review]
The build fails on this.

**Comment by agcolom** [comment]
@edent could it be the .idl extension? How about using https://www.khronos.org/registry/webgl/specs/latest/2.0/ instead?

**Comment by chaals** [comment]
Think because it doesn't point to a fragment :(

I'll chase it up.

**Review by edent — APPROVED** [review]

**Comment by edent** [comment]
@chaals I've updated this to be consistent with the others. Now works.

**Comment by chaals** [comment]
OK, thanks...

**Pull request merged**
