### PR TITLE
Update to canvas documentation

### LINKED ISSUE #1118: Don't use a wiki to define canvas context types
The spec currently [refers (non-normatively)](https://w3c.github.io/html/semantics-scripting.html#the-canvas-element) to [a WHATWG wiki page to define the context types for canvas](https://wiki.whatwg.org/wiki/CanvasContexts#content). These should just be defined in the spec, or written as HTML extensions.

(WHATWG themselevs don't rely on their wiki as a source).

### PR DESCRIPTION
**Pull request by edent**
Fixes #1118 

* Added webgl2 references.
* Removed obsolete link to WHATWG wiki.
* Tidied up table HTML

All feedback gratefully received.

### CODE REVIEW

**Comment by chaals** [comment]
Hopefully the reference changes will make the build happy - we will see soon :)

Also needs an entry in changes.include - I will do that now...

**Review by chaals — CHANGES_REQUESTED** [review]
There is something breaking the build in the biblio references that needs to be fixed - I am chasing that now.

I also added a note to the changelog.

**Review by chaals — APPROVED** [review]

**Comment by edent** [comment]
@cynthia that's a good point. I tested it, and it returns `null` as expected. I don't know how to test whether an error is fired anywhere.

**Comment by cynthia** [comment]
Yeah, I’m not sure if that clause in the spec is even valid.

**Pull request merged**
