### PR TITLE
Html5.1 implementation warnings

### PR DESCRIPTION
**Pull request by LJWatson**
Adding implementation warnings for probablySupportsContext, dir pseudo-class matching, & promises rejection handlers.

### CODE REVIEW

**Comment by chaals** [comment]
I would put these in a `p class="warning" - I think "warning" is clearer that "advisement".

Rather saying they _cannot_ be relied on, I would suggest that authors should use them with caution. This document will be around for a while, and some people will still use it when it is long out of date…

**Comment by LJWatson** [comment]
Pinging @Arronei - who recommended using advisement instead of warning.

**Comment by adanilo** [comment]
@arronei I've held of merging this until you advise if advisement is preferred...

**Comment by chaals** [comment]
Please make it a `<p class="warning">` instead of plain text saying advisement. Among other reasons, because I think "warning" is a much clearer word, and because we have used class="warning elsewhere"

**Pull request merged**
