### PR TITLE
Correct line ending and whitespace

### PR DESCRIPTION
**Pull request by arronei**
- Make sure all commits use the same line endings
- Trim unnecessary white space from files

### CODE REVIEW

**Comment by travisleithead** [comment]
I've not been very good about removing EOL whitespace, so I like that this change would fix that.

On line-ending normalization, I'm not sold. Is this something the other editors feel is necessary?

**Comment by travisleithead** [comment]
Hoping for feedback from editors not using Windows... @adanilo, @chaals ?

**Comment by chaals** [comment]
If this magically fixes errors I make, I'm all for it… (without checking, it seems like it does the Right Thing™ :) )

**Comment by adanilo** [comment]
LGTM - trimming is good. Line ending normalization doesn't bother me either way since my editor can cope.

**Pull request merged**
