### PR TITLE
Update the file

### PR DESCRIPTION
**Pull request by sarthak86**
This will give a description line in 1. section for "§8 The HTML syntax" this part.

### CODE REVIEW

**Comment by siusin** [comment]
Thanks @sarthak86 . Could you make your changes to the [introduction.include](https://github.com/w3c/html/blob/master/sections/introduction.include) in the `master` branch please? The files in the `gh-pages` branch is too large to load.

**Comment by sarthak86** [comment]
I need some help if u can

**Comment by sarthak86** [comment]
i am unable to edit there

**Comment by siusin** [comment]
hi @sarthak86 , 

could you try:
1) fork this repo, switch to the `master` branch;
2) edit the text on [introduction.include](introduction.include) to make the changes you suggested;
3) submit a pull request to the `master` branch of the W3C repo, the travis bot at github.com/w3c/html/ will generate an HTML page according to your pull.

let me know if any questions :)

**Comment by LJWatson** [comment]
Closing as replaced by #1602

**Pull request closed without merging**
