### PR TITLE
Editorial clarifications for i18n in number

### PR DESCRIPTION
**Pull request by chaals**
And a bit of cleaning stuff around that.

### CODE REVIEW

**Comment by chaals** [comment]
If taken in the master branch, fixes #343

**Comment by aphillips** [comment]
I have quickly read through the changes here. They partially satisfy some of I18N's comments, but I have some editorial nits:

> The same applies to the way numbers are written in different places. For example, in english-speaking countries "1,234" usually means "one thousand two hundred and thirty-four", while "1.234" means "one and two bundred and thirty-four thousandths", or "one point two three four". In many European languages the meanings are exactly reversed.

(Note typos: english->English, bundred->hundred)

I very much do not like the use of "English-speaking countries" and "European languages" here. The relevant thing that determines the format is generally cultural and the bit of jargon (which is used elsewhere here) that we mean is "locale". The same language may use very different rules for date, time, or number format (among other variations) and this is generally linked to regional variations or usages. I'd suggest instead:

> The same applies to the way numbers are written in different places. For example, in some locales, such as US English, "1,234" usually means "one thousand two hundred and thirty-four", while "1.234" means "one and two hundred and thirty-four thousandths", or "one point two three four", while in many other locales the meanings are exactly reversed.

In this paragraph:

> In HTML markup and <a>form submission</a> dates and times are always written in a format based on ISO-8601: Dates are "YYYY-MM-DD", as in "2003-02-01", times are "HH:MM[:SS][±HHMM]" as in "18:40" for 6.40pm, "00:01:01" for just after midnight, and "14:45+0200" for "a quarter to three, moscow time"

Is it strictly necessary to recapitulate the formats with examples here? While these are partial descriptions of the date and time formats, they are imprecise and incomplete. (In addition, the reference to Moscow time is an inappropriate jump from zone offset to time zone). Perhaps:

>  In HTML markup and <a>form submission</a> dates and times are always written in a locale-neutral format derived from the ISO-8601 standard. For example, dates are generally in a format such as `2016-06-19`.

In the following paragraph, this phrase: `...written with no seperator...` would be better to read `...written without grouping separators...`, as that is the technical term for it. Bear in mind: not all locales put grouping separators on every third digit either.

I also have some concerns about the discussion of contemporary vs. historical date/time values, but that should be in a separate issue.

**Comment by plehegar** [comment]
Note that the contemporary vs. historical date/time values have been removed from 5.1.

**Comment by plehegar** [comment]
Taken in master branch at b29a560 and 33f106a

**Pull request closed without merging**
