### PR TITLE
Add note for html and head element attribute usage suggestions

### PR DESCRIPTION
**Pull request by arronei**
- Add a note for recommending not to exceed 1024 bytes

Fix: #305

### CODE REVIEW

**Comment by arronei** [comment]
Hold off on merging this. I want to reword it.

**Comment by r12a** [comment]
@arronei you may already have this in mind, but where you say "keep the usage of attributes and their values on the <{head}> element to a  minimum and to not exceed 1024 bytes", the figure should be less than 1024 because you have to also take into account the doctype, the html tag and its attributes (and potentially a BOM).

**Comment by arronei** [comment]
@r12a I reworded the sentence a bit. It now focuses on the character encoding declaration within the first 1024 bytes.

**Comment by r12a** [comment]
Thanks @arronei.  It looks better.  I just hope that people won't take that as a licence to ignore the lang attribute, since that's is becoming increasingly important these days.

**Comment by travisleithead** [comment]
Works for me.

**Pull request merged**
