### PR TITLE
RFC update: 5988 -> 8288

### PR DESCRIPTION
**Pull request by plehegar**
Update the RFC to
  https://tools.ietf.org/html/rfc8288

### CODE REVIEW

**Comment by plehegar** [comment]
Looks like the bikeshed data (used by travis) is getting old "FATAL ERROR: Couldn't find 'RFC8288' in bibliography data."
RFC8288 does exist...

**Comment by LJWatson** [comment]
Thanks @plehegar . Can you delete your branch if this is done now?

**Comment by siusin** [comment]
The SpecRef database does contain [RFC8288](https://github.com/tobie/specref/blob/master/refs/ietf.json)... to fix the .travis build failure, we might need to switch to the latest version of Bikeshed.
@cynthia @stevefaulkner do you know why the 5.2 editors decided to use a snapshot of Bikeshed (9260eac3642631ba07cbb9e9b2936efe928153e3)? Will it break anything if we switch to the latest?

**Comment by cynthia** [comment]
I have no idea. Running an arbitrary snapshot is generally a bad idea anyway, as we will be getting PRs that work fine on contributor's machines and yet fail on travis. I think we should upgrade this given that it doesn't break 2000 other things.

**Comment by LJWatson** [comment]
Tend to agree that updating is worth trying. Though I do recall it breaking things in the past. Perhaps @TravisLeighthead and/or @ArronEi can shed some light...

**Pull request merged**
