### PR TITLE
Added about:html-kind URL for MP4 media track integration.

### PR DESCRIPTION
**Pull request by adanilo**
MP4 media track integration change as per issue #557 aligning with the WHATWG change whatwg/html@56ea222

### CODE REVIEW

**Comment by foolip** [comment]
Hi Alex, can you please ack the source in the commit message? The style in 43280f3a31b2f0bf007ec72621dde527ef81ed88 is a good example. This helps when trying to find things in w3c/html which also need some kind of action in whatwg/html. (It's been a while since I did any triage, though.)

**Comment by foolip** [comment]
Source in this case is https://github.com/whatwg/html/commit/56ea222aa35502dc2e8d7a83eb007e7f43559af7

**Comment by adanilo** [comment]
Sure, thanks for the pointer.

**Comment by foolip** [comment]
Can you also `git commit --amend` the actual commit? Thanks!

**Comment by adanilo** [comment]
Would like to, but out of office now and repos on my workstation. On leave for the next week so will have to wait.

**Pull request merged**
