### PR TITLE
Update 5.1 acknowledgements

### PR DESCRIPTION
**Pull request by chaals**
Err, this is another attempt to get this right :S

### CODE REVIEW

**Comment by chaals** [comment]
@arronei can you check this or re-assign please?

**Comment by stevefaulkner** [comment]
I don't understand why many names in the acknowledgements are being removed?

**Comment by chaals** [comment]
As mention in #247, to reset the list for HTML 5.2, and presumably subsequently for each further version.

There is no fair way to do acknowledgements. But on a per-version basis at least means people who came later aren't just drowned out by those who contributed to 5.0, and stops being looking for someone who contributed 15 years ago.

The names that are still there in the general thanks list - apart from the noted historical ones like past editors - are people who have contributed to the development specifically of the 5.2 spec already.

**Comment by stevefaulkner** [comment]
> The names that are still there in the general thanks list 

so no names have been removed, just re-organised?

**Comment by chaals** [comment]
> so no names have been removed, just re-organised?

**This** Pull Request just adds a number of names of people who contributed to the HTML 5.1 document, but were not acknowledged.

I presume that you mean to refer to #484 which is proposed for HTML 5.2, where almost all individual names have been removed. There is a general thanks to all past editors, WG participants, and WHATWG and its participants for all past work. A _few_ individual names have also been added where people who are not editors have made a direct contribution that affects the HTML 5.2 draft already, e.g. for things we have planned to take in 5.2 not 5.1. I presume that as we work on HTML 5.2 we will be adding more names. That is what was proposed in #247.

**Comment by stevefaulkner** [comment]
@chaals thanks for clarification

**Pull request merged**
