### PR TITLE
Update styles-html.css

### PR DESCRIPTION
**Pull request by RennyCat**
Minify css for faster .

### CODE REVIEW

**Comment by scottaohara** [comment]
while a minified CSS file might be nice, I don't think you should be overwriting the primary CSS file with the minified version. This will make it quite difficult for any potential future CSS updates.

**Comment by siusin** [comment]
I think it's a good idea to apply the minified CSS on gh-page branch. I'd suggest compressing the CSS file during the compile, maybe in the [deploy script](https://github.com/w3c/html/blob/master/.deploy-output.sh).

**Comment by cynthia** [comment]
I second @siusin 's remark about this.

**Comment by shwetank** [comment]
Agreed with @scottaohara and @siusin

**Comment by siusin** [comment]
Discussed in the 2nd Editor's call:
we should updated the multipage script to move the 1500+ lines of CSS in each page to a separated file.

**Comment by chaals** [comment]
The IPR issue here could be squashed, it is an editorial change. But since we are not going to solve the problem this way, I am closing and hope for a change to the deployment magi^Wscripts

**Pull request closed without merging**
