### PR TITLE
Clarify option/optgroup can be disabled

### LINKED ISSUE #1138: Should option/optgroup be listed in disabled attribute desc?
In reviewing the conditions for disabling a form control, I noticed that `option` and `optgroup` [were not listed as valid elements](https://www.w3.org/TR/html/sec-forms.html#enabling-and-disabling-form-controls-the-disabled-attribute) to receive the disabled attribute.

However, in the specific entries for [option](https://www.w3.org/TR/html/sec-forms.html#the-option-element) and [optgroup](https://www.w3.org/TR/html/sec-forms.html#the-optgroup-element), `disabled` is listed under allowed content attributes.

From reviewing past versions of the HTML5 specification, it appears that the individual listings of valid elements was dropped from [HTML4](https://www.w3.org/TR/html4/interact/forms.html#adef-disabled) to 5, with the [March 17, 2015 draft](https://www.w3.org/TR/2015/WD-html51-20150317/semantics.html#enabling-and-disabling-form-controls:-the-disabled-attribute) reinstating the list of valid elements.

As `option` and `optgroup` can receive the `disabled` attribute, should they be re-added to the valid element listing as well?

### PR DESCRIPTION
**Pull request by chaals**
Fix #1138

`option` and `optgroup` can be disabled. A [manual test](http://chaals.github.io/testcases/optgroup-disabled-manual.html)  works in Edge, Firefox, Opera (blink)

### CODE REVIEW

**Comment by LJWatson** [comment]
LGTM. @brucelawson or @edent, merge if you agree.

**Comment by ElenaCoffey** [comment]
Thank you so much

**Comment by devarshipant** [comment]
FYI -- Dev toolbar shows the active `optgroup` (Japanese Cars) as disabled (dimmed). Refer to the screenshot.

screen shot 2018-01-26 at 5 40 23 pm

**Comment by scottaohara** [comment]
FYI: the screen shot @devarshipant posted contains the following markup:
```
<select>
	<optgroup label="Swedish Cars" disabled>
		<option value="volvo">Volvo</option>
		<option value="saab">Saab</option>
	</optgroup>
	<optgroup label="German Cars">
		<option value="mercedes" disabled>Mercedes</option>
		<option value="audi" disabled>Audi</option>
	</optgroup>
	<optgroup label="Japanese Cars">
		<option value="Toyota">Toyota</option>
		<option value="honda">Honda</option>
	</optgroup>
	<option>Hyundai</option>
</select>
```

and is a screen shot of what appears to be the Safari developer tools.

Recreating the [markup and testing](https://codepen.io/scottohara/pen/KZOEPL), the `optgroup label="Japanese Cars"` is visually displayed and announced as "dimmed" with VoiceOver in Chrome and Safari.

This could possibly be a bug with webkit on macOS, as Firefox (windows and macos) & Internet Explorer & Chrome on windows display the `optgroup` appropriately.

**Comment by devarshipant** [comment]
Thanks @scottaohara. 

In Firefox (OSX), the _optgroup_ 'German Cars' is visibly active even though its _options_ are disabled. 
Here is the code:
`
    <optgroup label="German Cars">
    <option value="mercedes" disabled="" onclick="alert('click')">Mercedes</option>
    <option value="audi" disabled="" onclick="alert('click')">Audi</option>
  `

Screenshot showing the _optgroup_ (German Cars) as active when its options are disabled:

screen shot 2018-01-27 at 7 48 21 am

**Comment by scottaohara** [comment]
@devarshipant the `optgroup` in the german cars example makes some sense though, as it's the options within it that are disabled, not the grouping itself.  

That said, these issues seem to be more of a bug with implementation by Apple, rather than with the specification.  Would you like to [file a report](https://developer.apple.com/bug-reporting/), or shall I?

**Comment by devarshipant** [comment]
@scottaohara - thanks for the link to bug reporter. I will file it and let you know.

To summarize (in OSX), the issue is:
1. Parent is incorrectly **active** (when child is disabled) in _Firefox_. 
2. Parent is incorrectly **disabled (dimmed)** (when child is active) in _Safari_ and _Chrome_ .

**Comment by chaals** [comment]
@scottaohara wrote:

> @devarshipant the `optgroup` in the german cars example makes some sense though, as it's the options within it that are disabled, not the grouping itself.

Yes, according to spec the `optgroup` would not be disabled in that situation. In any event it doesn't *do* anything, so this seems reasonable. I can see a case for disabling it if all its children are disabled, but I can also see counter-cases, and it seems unnecessary complexity to me.

**Comment by devarshipant** [comment]
https://bugreport.apple.com/web/?problemID=36943719 filed at Apple.

Thanks @chaals, @scottaohara.

**Comment by scottaohara** [comment]
@annevk [has created a pull request](https://github.com/whatwg/html/pull/3415#issuecomment-361078261) that helps address my confusion here, in that `option` and `optgroup` are not "form controls", which was why they had been left out of this section.

I think the updates to both specs help address this confusion, but just wanted to call attention to the WHATWG wording.

**Pull request merged**
