### PR TITLE
Focus the dialog instead of the first item

### LINKED ISSUE #773: Update dialog focusing algorithm
After discussion here: https://github.com/whatwg/html/issues/1929 there is rough consensus to modify the existing dialog focus steps to make the `dialog` element focusable by default unless there is a control within the dialog that has an `autofocus` attribute.
Since i do not have the chops to work out how the spec needs to change to reflect this, would like those who may do to help @travisleithead @adanilo @arronei @cynthia any ideas?

the relevant spec bits:
https://w3c.github.io/html/interactive-elements.html#the-dialog-element
https://w3c.github.io/html/editing.html#focusing-steps

Firefox are in the process of implementing (dialog available behind flag in latest nightly) and I am working with the FF acc implementers to ensure that the implementation has good acc out of the box.

### PR DESCRIPTION
**Pull request by patricia-gallardo**
Fix #773 

Focus the dialog if there are noe autofocus items available, instead of picking the first focusable item

### CODE REVIEW

**Comment by chaals** [comment]
Needs to be tested - this is based on the agreement in #773 (and likewise in related https://github.com/whatwg/html/issues/1929) and predecessors from bugzilla

**Comment by LJWatson** [comment]
[Test case from MDN](https://mdn.mozillademos.org/en-US/docs/Web/HTML/Element/dialog$samples/Advanced_example?revision=1363411%20frame), and [support data from CIU](https://caniuse.com/#feat=dialog)

Test: when a ```<dialog>``` element is opened and the dialog does not contain a field with `autofocus` enabled, is keyboard focus placed on the ```<dialog>``` element itself?

Chrome desktop/mobile: no
Edge: `dialog` not supported
Firefox: ? (supported behind a flag)
IE: `dialog` not supported
Opera Mini: `dialog` not supported
Safari desktop/mobile: `dialog` not supported
Samsung Internet: no
UC Browser: ?

**Comment by patricia-gallardo** [comment]
Tested on Linux:
Chromium (Chrome/Vivaldi/Opera) all focus the dropdown
Firefox (after enabling in about:config dom.dialog_element.enabled) does not focus anything
I have not tested in Webkit (no mac) or Edge (no windows)
Both Webkit and Edge have issues open around the dialog element, however the support for the element still seems to be in its early stages.

**Review by chaals — APPROVED** [review]
Looks good. Note that the change is at risk because there is only one implementation at the moment.

**Pull request merged**
