### PR TITLE
Create html styles

### PR DESCRIPTION
**Pull request by rocky19998**

### CODE REVIEW

**Comment by edent** [comment]
Please don't create low-effort Hacktoberfest Pull Requests.

**Comment by scottaohara** [comment]
by my count this is at least the 9th junk pull request per @digitalocean's hacktoberfest.

**Comment by nschonni** [comment]
@scottaohara not saying it would stop them, but maybe a PULL_REQUEST_TEMPLATE.md might help

**Comment by scottaohara** [comment]
@nschonni a template is a good idea.  but yeh, doubtful it'd derail anyone who's looking to just get a free shirt with needless PRs.

**Pull request closed without merging**
