### PR TITLE
Update paragraph description

### LINKED ISSUE #1112: Confusing statement regarding the content model of <p> in the "Changes" section in HTML5.2
The ["Fixing bugs and matching reality better" subsection](https://www.w3.org/TR/html52/changes.html#fixing-bugs-and-matching-reality-better) of the "Changes" section in the HTML5.2 spec has the following statament:

> The following constructions are no longer valid HTML:
> * Inline blocks, inline tables, or floated and positioned block-level elements as children of a `<p>` element.

As far as I understand, it refers to the clarification issue #763 (and the related PR #838).

This statement looks very confusing to me because it seems to imply that in previous editions of HTML these elements _were_ valid as children of a `<p>` element when formatted that way, which hardly could be the case because CSS doesn't affect the content model (and the rules of parsing, which occurs long before any CSS is applied). Also, it seems to imply that the concept of "block-level elements" exists in HTML (not CSS), which also can lead to wrong conclusions and confusion since too many educational resources still operate the HTML 4 concept of "block vs. inline elements" and not all modern HTML elements can fall into one of these categories.

Wouldn't it be better to change the wording so that it would be clear that 1) the appearance of the element is controlled by CSS and doesn't affect its kind and content model, and 2) therefore, elements not allowed to be children of `<p>` can't be nested in it _regardless their styling,_ even if they are _formatted_ as "inline" or "inline-something"?

### PR DESCRIPTION
**Pull request by chaals**
Clarify explanation of what can be a child and what cannot, and why.
Mostly fix #1112

### CODE REVIEW

**Comment by chaals** [comment]
@UPD:(sorry, wrong user) do you want to have a look at this?

**Review by Alohci — COMMENTED** [review]
Comment retracted.

**Comment by chaals** [comment]
@SelenIT does this look right?

**Comment by SelenIT** [comment]
@chaals, thanks a lot for your effort and sorry for taking so much your time for this, but... after re-reading this whole section, I tend to think that it would be better just to remove that note at all.

The Content model definition of the `<p>` element already disallows non-phrasing elements as its children. The "Tag omission in text/html" subsection, which is already there, effectively lists these elements explicitly (it's quite clear that if some element implicitly closes the paragraph, then this element can't be inside this paragraph, and that list doesn't say anything about the "rendering" of these elements, clearly meaning that this rule is universal and doesn't depend on it). Other elements whose Content model is "Phrasing content" usually don't have such special note either, the WHATWG spec also doesn't have it, so probably it would be better to reduce the divergence rather than to increase it.

However, it might be useful to highlight that the "paragraph" that the `<p>` element represents means _the paragraph in terms of the HTML5 spec,_ not the colloquial meaning of this term. Maybe adding "_as defined in this specification_" after the link to the paragraph definition would be enough to make clearer what does "paragraph" mean here?

**Comment by Alohci** [comment]
It's worth noting that "cannot be children" is a bit strong for section 4, since it's only a text/html parser imposition. Neither the XML parser, nor document sub-trees formed by JavaScript impose this restriction. "must not be descendants" would be more accurate.

**Comment by SelenIT** [comment]
@Alohci, I agree that "cannot be..." is an oversimplification. But from my practical experience and many Stackoverflow questions (like [this](https://stackoverflow.com/q/10601345/2533215) or [this](https://stackoverflow.com/q/32611601/2533215)) one of the most frequent troubles with the `<p>` element for the authors is when they try to place something like a list or a heading inside the paragraph and get surprised that in the DOM this element is the next sibling of the `<p>` element rather than its child. Just postulating that such nesting is "not valid" wouldn't stop some authors who share the popular "validity doesn't matter" attitude from attempting it, while explaining why they simply can't achieve it under the most common scenario probably would. And people who serve their markup under XML MIME-type or build the DOM with JavaScript more likely know what they do, and if they need to work around a particular limitation, they might have a reason for that.

That said, I don't insist that the element definition in the spec is the best place for such a caution. The "must not be descendants" would not add anything significant to the "Content model" section, elements that would end up siblings of `<p>` instead of its children due to implicit tag closing under the text/html parsing are also listed right there. I tend to think that providing an incorrect example with the medium-sized explanation why it is incorrect (with this HTML parsing feature among other reasons) should be enough. It probably would be useful to elaborate the definition of the "paragraph" concept in the HTML5 terms and make the link to this definition more obvious in the `<p>` element definition. Maybe it's worth to propose that change in both WHATWG and W3C specs?

**Comment by Alohci** [comment]
@SelenIT - Yes, that seems like a much more useful approach to me.

**Comment by SelenIT** [comment]
I'm so sorry that I hadn't propose my own version before that change was accepted. I saw the "not ready for merge" label and hoped that I have more time to work it out. My plan was to update the "paragraph" term definition to make it more clear that it is "not a logical concept, but a structural one", provide a clear link to it (as it's currently done, with "as defined in this specification" addition), and remove all mentioning of the "rendering" (even "typical") to prevent any speculation that CSS can anyhow affect the ability of the elements to be children of `p`. Ideally, I wanted to make these changes synchronously to WHATWG (I [just discussed](https://github.com/whatwg/html/issues/2807#issuecomment-361875921) it there) and W3C specs, to avoid increasing of unnecessary divergence between them.

Maybe it's not too late to roll the current change back and to think about it a bit more, taking into account @Alohci's [comment](https://github.com/w3c/html/pull/1113#issuecomment-353096457) and other reasons? Given the popularity of the `p` element, it's not good to make updates to it in a hurry, I don't want to repeat the situation that already led to #1112.

**Comment by chaals** [comment]
@SelenIT I don't think we will roll the change back, but you are welcome to propose further improvements that make it more clear still what we mean - given the age, popularity, and wide use of the `p` element we can always accept a better explanation.

By the way we try to assign milestones so people can get a sense of when we expect to do something concrete - if there is an assignee and a milestone for an issue then we will feel bad if we **don't** close the issue by the milestone date (or a bit before).

**Pull request merged**
