### PR TITLE
Editorial: add GET & POST descriptions

### LINKED ISSUE #1447: No description of the attribute method
No description of the attribute **method** of form element what is and how works is:
GET
POST
And when should use GET and when POST and difference between them.

### PR DESCRIPTION
**Pull request by scottaohara**
fixes #1447 

add short descriptions of GET and POST values.

other minor char length cleanup for source file.

### CODE REVIEW

**Comment by siusin** [comment]
How about adding a link to the definition for these terms in the HTTP IETF standard?
POST, https://tools.ietf.org/html/rfc7231#section-4.3.3
GET, https://tools.ietf.org/html/rfc7231#section-4.3.1

**Comment by scottaohara** [comment]
Yah, i'd be in favor of that

**Comment by siusin** [comment]
@scottaohara 
An ideal way to add these links would be defining it in the single-page.bs document, try put an anchor in the rfc7231 section (L756):
```
text: HTTP GET; type: dfn; url: section-4.3.1
text: HTTP POST; type: dfn; url: section-4.3.3
```

And use it in the other part of the spec as
```
<a>HTTP POST</a>
<a>HTTP GET</a>
```

**Comment by siusin** [comment]
@scottaohara ++

I think it's ready to merge once the conflicts get resolved.

**Comment by scottaohara** [comment]
ah boo.  i'll get that taken care of

**Comment by scottaohara** [comment]
Thank you @siusin.  I'll merge this once checks finish.

**Comment by scottaohara** [comment]
@siusin ok, seems something is going odd with our build process as it keeps reporting the following:
```
<pre path="sections/introduction.include" line-number="1129" class="include"></pre>
LINE 1129: Couldn't find include file 'sections/introduction.include'. Error was:
global name 'io' is not defined
ERR Did not generate, due to fatal errors
```

**Comment by siusin** [comment]
Weird, I tried building the spec with the latest version of bikeshed locally, it worked.

I'm guessing the travis bot only recognised the files got changed in this pull so it failed to find the other files in the repo. Will dig deeper into the problem later.

**Comment by siusin** [comment]
Also see [bikeshed issue #1320](https://github.com/tabatkins/bikeshed/issues/1320).

**Pull request merged**
