### PR TITLE
Allow nesting headers and footers but warn against it

### PR DESCRIPTION
**Pull request by plehegar**
#273

@stevefaulkner @cyns you probably want to check this.

### CODE REVIEW

**Comment by stevefaulkner** [comment]
I disagree with this change, I don't see what adavantage it provides, it only appears to make the semantics of header and footer more ambiguous

**Comment by ZoeBijl** [comment]
I agree with Steve, I see no benefit from this change.

**Comment by plehegar** [comment]
@chaals ?

**Comment by travisleithead** [comment]
I could swing either way on this one. The net effect only determines the legitimacy of headers-in-headers in the eyes of validation. So if we don't fix it, the reporter's markup becomes illegitimate, and his argument is that it has legitimacy. If we don't fix it, I'd still want to see a note covering his scenario and how to "legitimately" work around it.

**Comment by LJWatson** [comment]
FWIW I would prefer that nested headers be considered illegitimate, but for a note to be included (as @travisleithead suggests) to explain how to meet the use case legitimately.

**Comment by plehegar** [comment]
See also https://github.com/w3c/html/pull/429

**Comment by travisleithead** [comment]
Given the choice between this change and #429, I think #429 makes more semantic sense. A new sectioning block creates an opportunity for a new header/footer pair--as deeply nested as you want to keep creating sections. Seems to make sense to me.

**Comment by plehegar** [comment]
Feel free to reopen if you feel strongly.

**Pull request closed without merging**
