### PR TITLE
Update changes

### PR DESCRIPTION
**Pull request by chaals**
Remove editorial cleanups, note Plugin API was shifted to obsolete.

### CODE REVIEW

**Comment by chaals** [comment]
Aargh. This updates the changes and acknowledgements, and somehow I failed to request it before the PR draft was published.

Since it is editorial, I suggest merging it before producing the final version... and I think we should merge the same changes to master

**Comment by LJWatson** [comment]
It looks like this PR wants to merge into the html5.2 branch. If so, you'll need to change your base to master. If it's intended to merge into master (for HTML5.3), then it's been superceded by [this commit](https://github.com/w3c/html/commit/f9d9f969f3ed95f8fcb28db799e809f15fb76ee1) which updates the changelog for 5.3 changes only.

**Comment by chaals** [comment]
Yes, it is explicitly meant for the 5.2 branch. @siusin should I try to update this, or throw it away and assume you have / will get the details into 5.2 ?

**Comment by chaals** [comment]
@siusin ping?

**Review by siusin — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
