### PR TITLE
Clarify the charset constraints on email addresses

### LINKED ISSUE #538: "valid email address" doesn't allow IDNs…
The definition of a [valid email address](https://w3c.github.io/html/sec-forms.html#valid-e-mail-address) only allows for ascii letters, digits, and hyphens in domain names, and only ascii printable characters before the @ sign. This doesn't match reality, which now includes IDNs.

Should we insist on putting punycode everywhere, or should we try to hide that from users and specify how to make internationalised email addresses?

### PR DESCRIPTION
**Pull request by chaals**
Fix #538
See also #845

This is mostly editorial. It changes one requirement,
from "user agents **may** present punycode as IDNs in the interface" to a **should**.

The rest of the change is to abstract common requirements for different aspects, and better explain
what the requirements actually *mean*.

### CODE REVIEW

**Review by chaals — COMMENTED** [review]
Hmm. This should note the issue with homographs and phishing, and point out that UAs should be wary of that.

Which should also go into the security considerations...

**Comment by chaals** [comment]
I think I've resolved the merge conflicts - they were nearly all whitespace variation.

(Isn't there some magic for saying this is BS-HTML-markdown so irrelevant whitespace changes don't get flagged?)

**Comment by cynthia** [comment]
As discussed over IRC (on html-editors) with the recent issue of lookalike domains abusing IDNs, we should probably touch on that topic before bringing this in.

That said, this is for user input (and considering that wild content mostly uses text types for email, this change probably doesn't introduce additional security issues) - so if it's something that is needed for 5.2 I think it'd be okay to merge this change and address the lookalike IDN issue separately.

**Comment by chaals** [comment]
This is for input. If a user can be tricked into typing from two different scripts, there are bigger problems and easier ways to attack that user.

It's feasible to check whether mixed scripts are being used, and warn the user - and in many cases TLDs prohibit registration of mixed-script second-level domain names.

If browsers implement this, they can compare a domain to see if it's *like* something in a user's email contacts or not, and provide warnings to users about phishing attempts - which offers better protection than assuming people checked punycode strings… Although there may be a possibility that someone can reverse-engineer browser implementation to enhance spear-phishing or information-gathering, I don't see a good way of doing that...

(for anyone wondering, the issue is that w3.org and wЗ.org look the same, but the second one uses a cyrillic character as it's second letter, which happens to look like a 3. There are a lot of similar pairs, which makes Internationalised Domain Names frighten people who think we might be able to stick to ASCII for safety - and those of us who don't think that is feasible either).

My preference is to merge this, but to ask for thoughtful security review through CR, on the off-chance that someone convinces us to back it out:
/@mkwest @r12a @wseltzer

**Comment by chaals** [comment]
…But I would be sympathetic to a review that said "explain the issue in the text before it gets merged".

**Comment by Jannelson** [comment]
LGTM Chaals

**Comment by adanilo** [comment]
LGTM

**Pull request merged**
