### PR TITLE
Update bikeshed to latest

### PR DESCRIPTION
**Pull request by arronei**
- Remove old data files
- update bikeshed to use latest version

### CODE REVIEW

**Comment by arronei** [comment]
Fix #121

**Comment by travisleithead** [comment]
This changes moves us from using a static copy of the bikeshed to using the live current version. 

The benefit: 
- We now have the correct license info.
- We have updated fixes to improve linking/WebIDL parser changes.
- Correct linking errors with header info
- updated style sheet references

The downside:
- If bikeshed pushes something that breaks us, we are dependent on a fix from them in order to resume building the spec.

@arronei has tried to understand why the previous model wasn't working with the most recent changes to bikeshed but has not succeeded. I'd like to see consensus with merging this commit before we make this change. Since I develop with a local (stale) copy of bikeshed for my local changes, this won't impact me directly, but it could hinder publication...

**Comment by arronei** [comment]
You wouldn't have to use a stale copy of bikeshed any longer you could use the latest for your local editing. This would simplify your process for bikeshed and identify errors in editing earlier in the process before doing a PR.

**Comment by travisleithead** [comment]
Please update the readme file first.

**Comment by travisleithead** [comment]
Fantastic.

**Pull request merged**
